# Generated by Django 3.0.7 on 2020-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('expire_at',),
            },
        ),
    ]
